# Generated by Django 3.1.6 on 2021-02-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210206_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
